domain: lajilao.com
title: åƒåœ¾ä½¬
title_ext: åªæƒ³ç§€ç§€

contacts:
  - icon: "fa fa-envelope"
    url: "mailto:hi@nai.ba"
    text: hi@nai.ba
  - icon: "fa fa-qq"
    text: 2088888812
  # - icon: "fa fa-wechat"
  #   text: 2088888812

domains:
  - domain: nai.ba
    description: "@å¥¶çˆ¸"
  - domain: 5.nu
    description: "@äº”å“¥"
  - domain: nb2.com
    description: "@å¥¶æŠŠå„¿"
  - domain: lifelonglearni.ng
    description: "@ç»ˆèº«å­¦ä¹ "
  - domain: git.cm
    description: "@Git"
  - domain: xzg.com.cn
    description: "@å°æŒæŸœ"
  - domain: solitud.es
    description: "@äº«å—å­¤ç‹¬"
  - domain: naibahq.com
    description: "@ä¸€èˆ¬é¡¹ç›®ä½¿ç”¨"
  - domain: gg0.com
    description: "@GG"
  - domain: boringbay.com
    description: "@æ— èŠ"
  - domain: jf4.com
    description: "@é£“é£"
  - domain: gk4.com
    description: "@æœå£³"
  - domain: jg0.com
    description: "@åšæœ"
  - domain: pi4.com
    description: "@çš®"
  - domain: jn4.com
    description: "@è§£è…»"
  - domain: jh4.com
    description: "@æ±Ÿæ¹–"
  - domain: oh1.com
    description: "@æ¬§è€¶âœŒï¸"
  - domain: lajilao.com
    description: "@åƒåœ¾ä½¬"
  - domain: p14yground.com
    description: "@Playground"
    price: 500w
  - domain: thebigpicture.cn
    description: "@æ ¼å±€æ‰“å¼€ğŸ«´"
